import { Poppins, Fuzzy_Bubbles, Montserrat } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Poppins({ weight: ['200', '300', '400', '500', '600', '700', '800', '900'], subsets: ["latin"] });

const fuzzyBubbles = Fuzzy_Bubbles({ weight: ['400', '700'], subsets: ["latin"], variable: '--fuzzy-bubbles' });
const montserrat = Montserrat({ weight: ['200', '300', '400', '500', '600', '700', '800', '900'], subsets: ["latin"], variable: '--montserrat' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>

      </Head>
      <body className={`${inter.className} ${fuzzyBubbles.variable} ${montserrat.variable}`}>{children}</body>
    </html>
  );
}
